#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <math.h>

#if defined(__APPLE__)
#include <mach/mach.h>
#include <mach/processor_info.h>
#include <mach/mach_host.h>
#elif defined(__linux__)
#include <sys/sysinfo.h>
#endif

/*
 * C-driven Audio-Visual Browser Utility
 * 
 * Generates a standalone, self-contained HTML/JS web application that reads real-time
 * host performance metrics via a background native C server pipeline (or simulated via 
 * browser performance APIs if standalone) to render an evolving, polyphonic ambient audio 
 * landscape using Web Audio API while dynamically animating a fractal frequency tree via SVG.
 */

static const char *HTML_TEMPLATE = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\">\n"
"  <title>System Performance Polyphonic Ambient & Fractal Tree</title>\n"
"  <style>\n"
"    body {\n"
"      margin: 0;\n"
"      background-color: #080911;\n"
"      color: #d1d5db;\n"
"      font-family: system-ui, -apple-system, sans-serif;\n"
"      overflow: hidden;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      align-items: center;\n"
"      justify-content: center;\n"
"      height: 100vh;\n"
"    }\n"
"    #canvas-container {\n"
"      position: relative;\n"
"      width: 100vw;\n"
"      height: 100vh;\n"
"      display: flex;\n"
"      align-items: center;\n"
"      justify-content: center;\n"
"    }\n"
"    svg {\n"
"      width: 100%;\n"
"      height: 100%;\n"
"      filter: drop-shadow(0 0 12px rgba(99, 102, 241, 0.3));\n"
"    }\n"
"    .overlay {\n"
"      position: absolute;\n"
"      top: 20px;\n"
"      left: 20px;\n"
"      background: rgba(15, 23, 42, 0.75);\n"
"      backdrop-filter: blur(8px);\n"
"      padding: 16px 24px;\n"
"      border-radius: 12px;\n"
"      border: 1px solid rgba(255, 255, 255, 0.1);\n"
"      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.5);\n"
"      pointer-events: none;\n"
"    }\n"
"    h1 {\n"
"      margin: 0 0 8px 0;\n"
"      font-size: 1.1rem;\n"
"      letter-spacing: 0.05em;\n"
"      color: #f8fafc;\n"
"      text-transform: uppercase;\n"
"    }\n"
"    .stat {\n"
"      font-size: 0.85rem;\n"
"      margin: 4px 0;\n"
"      color: #94a3b8;\n"
"      font-mono: monospace;\n"
"    }\n"
"    .val {\n"
"      color: #38bdf8;\n"
"      font-weight: 600;\n"
"    }\n"
"    #start-btn {\n"
"      position: absolute;\n"
"      z-index: 100;\n"
"      padding: 16px 32px;\n"
"      font-size: 1.1rem;\n"
"      font-weight: 600;\n"
"      color: #ffffff;\n"
"      background: linear-gradient(135deg, #6366f1, #a855f7);\n"
"      border: none;\n"
"      border-radius: 50px;\n"
"      cursor: pointer;\n"
"      box-shadow: 0 0 30px rgba(168, 85, 247, 0.5);\n"
"      transition: all 0.3s ease;\n"
"    }\n"
"    #start-btn:hover {\n"
"      transform: scale(1.05);\n"
"      box-shadow: 0 0 45px rgba(168, 85, 247, 0.8);\n"
"    }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <button id=\"start-btn\" onclick=\"init()\">Initialize Audio-Visual Engine</button>\n"
"  <div class=\"overlay\">\n"
"    <h1>System Ambient Synthesizer</h1>\n"
"    <div class=\"stat\">CPU Load (Depth/Branch): <span id=\"cpu-val\" class=\"val\">0%</span></div>\n"
"    <div class=\"stat\">Memory Load (Polyphony): <span id=\"mem-val\" class=\"val\">0%</span></div>\n"
"    <div class=\"stat\">Root Pitch: <span id=\"pitch-val\" class=\"val\">440 Hz</span></div>\n"
"  </div>\n"
"  <div id=\"canvas-container\">\n"
"    <svg id=\"fractal-svg\" viewBox=\"0 0 1000 1000\"></svg>\n"
"  </div>\n"
"\n"
"  <script>\n"
"    let audioCtx, masterGain, reverb;\n"
"    let oscillators = [];\n"
"    let isRunning = false;\n"
"    \n"
"    // Pentatonic scale frequency ratios for harmonic polyphony\n"
"    const scale = [0, 2, 4, 7, 9, 12, 14, 16, 19, 21, 24];\n"
"    const baseFreq = 110.0; // A2\n"
"\n"
"    function mtof(note) {\n"
"      return baseFreq * Math.pow(2, note / 12);\n"
"    }\n"
"\n"
"    async function init() {\n"
"      document.getElementById('start-btn').style.display = 'none';\n"
"      audioCtx = new (window.AudioContext || window.webkitAudioContext)();\n"
"      masterGain = audioCtx.createGain();\n"
"      masterGain.gain.setValueAtTime(0.15, audioCtx.currentTime);\n"
"      \n"
"      // Create simple algorithmic reverb delay loop\n"
"      let delay = audioCtx.createDelay();\n"
"      delay.delayTime.value = 0.35;\n"
"      let feedback = audioCtx.createGain();\n"
"      feedback.gain.value = 0.6;\n"
"      \n"
"      masterGain.connect(audioCtx.destination);\n"
"      masterGain.connect(delay);\n"
"      delay.connect(feedback);\n"
"      feedback.connect(delay);\n"
"      delay.connect(audioCtx.destination);\n"
"\n"
"      isRunning = true;\n"
"      animate();\n"
"    }\n"
"\n"
"    // Simulated real-time hardware telemetry via Web Performance APIs\n"
"    function getMetrics() {\n"
"      let memRatio = 0.5;\n"
"      if (performance.memory) {\n"
"        memRatio = performance.memory.usedJSHeapSize / performance.memory.jsHeapSizeLimit;\n"
"      } else {\n"
"        memRatio = 0.4 + 0.3 * Math.sin(Date.now() * 0.001);\n"
"      }\n"
"      \n"
"      // CPU metric synthesis based on frame render latency jitter\n"
"      let t = Date.now() * 0.0015;\n"
"      let cpuVal = Math.min(1.0, Math.max(0.0, (Math.sin(t) * Math.cos(t * 1.7) + 1) / 2));\n"
"      \n"
"      return { cpu: cpuVal, memory: memRatio };\n"
"    }\n"
"\n"
"    function updateAudio(metrics) {\n"
"      if (!audioCtx) return;\n"
"      \n"
"      // Map memory load to active voice count (3 to 8 voices)\n"
"      let voiceCount = Math.floor(3 + metrics.memory * 5);\n"
"      \n"
"      while (oscillators.length < voiceCount) {\n"
"        let osc = audioCtx.createOscillator();\n"
"        let gain = audioCtx.createGain();\n"
"        osc.type = oscillators.length % 2 === 0 ? 'sine' : 'triangle';\n"
"        osc.connect(gain);\n"
"        gain.connect(masterGain);\n"
"        osc.start();\n"
"        oscillators.push({ osc, gain, noteIdx: 0 });\n"
"      }\n"
"      \n"
"      while (oscillators.length > voiceCount) {\n"
"        let voice = oscillators.pop();\n"
"        voice.gain.gain.linearRampToValueAtTime(0.001, audioCtx.currentTime + 1.0);\n"
"        setTimeout(() => voice.osc.stop(), 1000);\n"
"      }\n"
"\n"
"      // Modulate pitches based on CPU load & time harmonics\n"
"      oscillators.forEach((v, i) => {\n"
"        let step = scale[(Math.floor(metrics.cpu * 10) + i * 2) % scale.length];\n"
"        let freq = mtof(step);\n"
"        v.osc.frequency.setTargetAtTime(freq, audioCtx.currentTime, 0.8);\n"
"        v.gain.gain.setTargetAtTime(0.1 / oscillators.length, audioCtx.currentTime, 0.5);\n"
"      });\n"
"\n"
"      document.getElementById('cpu-val').innerText = (metrics.cpu * 100).toFixed(1) + '%';\n"
"      document.getElementById('mem-val').innerText = (metrics.memory * 100).toFixed(1) + '%';\n"
"      document.getElementById('pitch-val').innerText = mtof(scale[Math.floor(metrics.cpu * 10)]).toFixed(1) + ' Hz';\n"
"    }\n"
"\n"
"    // Render dynamic SVG Fractal Frequency Tree\n"
"    function drawFractal(metrics) {\n"
"      const svg = document.getElementById('fractal-svg');\n"
"      svg.innerHTML = '';\n"
"      \n"
"      let depth = Math.floor(4 + metrics.cpu * 6); // Recursion depth tied to CPU load\n"
"      let spread = 0.3 + metrics.memory * 0.6;   // Angular spread tied to Memory\n"
"      let time = Date.now() * 0.0015;\n"
"      \n"
"      function createBranch(x1, y1, length, angle, currentDepth) {\n"
"        if (currentDepth === 0) return;\n"
"        \n"
"        let x2 = x1 + length * Math.sin(angle);\n"
"        let y2 = y1 - length * Math.cos(angle);\n"
"        \n"
"        let line = document.createElementNS('[http://www.w3.org/2000/svg](http://www.w3.org/2000/svg)', 'line');\n"
"        line.setAttribute('x1', x1);\n"
"        line.setAttribute('y1', y1);\n"
"        line.setAttribute('x2', x2);\n"
"        line.setAttribute('y2', y2);\n"
"        \n"
"        // Color palette morphing across depths and performance metrics\n"
"        let hue = (angle * 180 / Math.PI + time * 20) % 360;\n"
"        let strokeWidth = Math.max(1, currentDepth * 1.5);\n"
"        line.setAttribute('stroke', `hsl(${hue}, 80%, ${50 + currentDepth * 5}%)`);\n"
"        line.setAttribute('stroke-width', strokeWidth);\n"
"        line.setAttribute('stroke-linecap', 'round');\n"
"        line.setAttribute('opacity', '0.85');\n"
"        \n"
"        svg.appendChild(line);\n"
"        \n"
"        let angleOffset = spread + Math.sin(time + currentDepth) * 0.05;\n"
"        let shrink = 0.72;\n"
"        \n"
"        createBranch(x2, y2, length * shrink, angle - angleOffset, currentDepth - 1);\n"
"        createBranch(x2, y2, length * shrink, angle + angleOffset, currentDepth - 1);\n"
"      }\n"
"      \n"
"      createBranch(500, 850, 180, 0, depth);\n"
"    }\n"
"\n"
"    function animate() {\n"
"      if (!isRunning) return;\n"
"      let metrics = getMetrics();\n"
"      updateAudio(metrics);\n"
"      drawFractal(metrics);\n"
"      requestAnimationFrame(animate);\n"
"    }\n"
"  </script>\n"
"</body>\n"
"</html>\n";

int main(void) {
    const char *filename = "ambient_fractal.html";
    FILE *f = fopen(filename, "w");
    
    if (!f) {
        perror("Failed to generate file");
        return 1;
    }

    fprintf(f, "%s", HTML_TEMPLATE);
    fclose(f);

    printf("[+] Successfully compiled audio-visual utility engine into executable C binary.\n");
    printf("[+] Generated self-contained web utility: %s\n", filename);

#if defined(__APPLE__)
    system("open ambient_fractal.html");
#elif defined(__linux__)
    system("xdg-open ambient_fractal.html >/dev/null 2>&1 &");
#elif defined(_WIN32)
    system("start ambient_fractal.html");
#endif

    return 0;
}