-- mandala.lua
-- A LOVE2D program that visualises audio (simulated) as an evolving mandala.
-- Each frequency peak spawns a glyph generated by an L‑system.
-- The mandala state is saved inside the PNG file (steganography) and restored on start.

local json = require "dkjson"        -- tiny JSON library (include dkjson.lua in same folder)
local stateFile = "mandala.png"      -- image file that also stores hidden state
local hiddenMarker = "LUA_STATE:"   -- marker to locate hidden data

-- Simple L‑system definition
local axiom = "F"
local rules = { F = "F[+F]F[-F]F" }  -- classic fractal tree
local angle = math.rad(25)
local iterations = 3

-- Simulated audio spectrum (replace with real input if available)
local function getSpectrum()
    local spectrum = {}
    for i = 1, 8 do
        spectrum[i] = math.random()   -- random peak intensity [0,1]
    end
    return spectrum
end

-- Generate glyph string using L‑system
local function generateGlyph()
    local str = axiom
    for i = 1, iterations do
        str = (str:gsub(".", function(c) return rules[c] or c end))
    end
    return str
end

-- Convert glyph string to a set of line segments
local function glyphToLines(glyph, x, y, size)
    local stack = {}
    local dir = -math.pi/2
    local pos = {x=x, y=y}
    local lines = {}
    for c in glyph:gmatch"." do
        if c == "F" then
            local nx = pos.x + math.cos(dir)*size
            local ny = pos.y + math.sin(dir)*size
            table.insert(lines, {pos.x, pos.y, nx, ny})
            pos.x, pos.y = nx, ny
        elseif c == "+" then
            dir = dir + angle
        elseif c == "-" then
            dir = dir - angle
        elseif c == "[" then
            table.insert(stack, {x=pos.x, y=pos.y, d=dir})
        elseif c == "]" and #stack>0 then
            local s = table.remove(stack)
            pos.x, pos.y, dir = s.x, s.y, s.d
        end
    end
    return lines
end

-- Load hidden state from PNG (if present)
local function loadState()
    local f = io.open(stateFile, "rb")
    if not f then return {} end
    local data = f:read("*a")
    f:close()
    local markerPos = data:find(hiddenMarker, 1, true)
    if markerPos then
        local jsonStr = data:sub(markerPos + #hiddenMarker)
        local obj, pos, err = json.decode(jsonStr, 1, nil)
        if obj then return obj end
    end
    return {}
end

-- Save current mandala state into PNG (appends hidden JSON)
local function saveState(state)
    -- render current canvas to image
    local screenshot = love.graphics.newScreenshot()
    local encoded = screenshot:encode("png")
    -- append hidden data
    local f = io.open(stateFile, "wb")
    f:write(encoded)
    local jsonStr = json.encode(state)
    f:write(hiddenMarker .. jsonStr)
    f:close()
end

-- Global mandala data
local mandala = {
    glyphs = {},   -- each entry: {x,y,size,lines}
    seed = 0
}

function love.load()
    love.window.setTitle("Audio‑driven Mandala")
    love.window.setMode(800, 800)
    mandala = loadState()
    if not mandala.glyphs then mandala.glyphs = {} end
    love.graphics.setBackgroundColor(0, 0, 0)
end

function love.update(dt)
    -- Simulate getting audio peaks
    local spectrum = getSpectrum()
    for i, peak in ipairs(spectrum) do
        if peak > 0.7 then
            -- spawn a new glyph at polar coordinates based on frequency bin
            local radius = 200 + i*10
            local theta = i * (2*math.pi/ #spectrum) + mandala.seed
            local gx = 400 + radius * math.cos(theta)
            local gy = 400 + radius * math.sin(theta)
            local size = 5 + peak*10
            local glyphStr = generateGlyph()
            local lines = glyphToLines(glyphStr, gx, gy, size)
            table.insert(mandala.glyphs, {lines=lines})
        end
    end
    mandala.seed = mandala.seed + dt*0.1
end

function love.draw()
    love.graphics.setColor(1,1,1,0.8)
    for _,g in ipairs(mandala.glyphs) do
        for _,ln in ipairs(g.lines) do
            love.graphics.line(ln[1], ln[2], ln[3], ln[4])
        end
    end
end

function love.keypressed(key)
    if key == "s" then
        saveState(mandala)
    elseif key == "escape" then
        love.event.quit()
    end
end