import Foundation
import AppKit
import AudioToolbox
import AVFoundation

// MARK: - AST & Obfuscation Domain Models

/// Represents a node in the Abstract Syntax Tree (AST) derived from source code analysis.
final class ASTNode {
    let type: NodeType
    let identifier: String
    var children: [ASTNode]
    
    enum NodeType: String {
        case program, function, controlFlow, variable, expression, statement
    }
    
    init(type: NodeType, identifier: String, children: [ASTNode] = []) {
        self.type = type
        self.identifier = identifier
        self.children = children
    }
}

/// A musical note generated by translating AST structure into audio dimensions.
struct MIDINote {
    let pitch: UInt8       // MIDI Pitch (0-127), calculated from AST Node Depth
    let velocity: UInt8    // MIDI Velocity (0-127), calculated from Spectral Energy
    let duration: Double   // Duration in seconds, calculated from Cyclomatic Complexity
    let timestamp: Double  // Offset time in seconds
}

// MARK: - Parser & Obfuscation Analyzer

/// Tokenizes and parses source code into an AST while measuring complexity metrics.
final class SourceAnalyzer {
    
    /// Parses a raw source code string into an AST structure.
    func buildAST(from source: String) -> ASTNode {
        let root = ASTNode(type: .program, identifier: "RootProgram")
        let lines = source.components(separatedBy: .newlines)
        
        var currentParent = root
        var stack: [ASTNode] = [root]
        
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty { continue }
            
            let nodeType: ASTNode.NodeType
            if trimmed.contains("func") || trimmed.contains("def") {
                nodeType = .function
            } else if trimmed.contains("if") || trimmed.contains("for") || trimmed.contains("while") || trimmed.contains("switch") {
                nodeType = .controlFlow
            } else if trimmed.contains("let") || trimmed.contains("var") || trimmed.contains("=") {
                nodeType = .variable
            } else {
                nodeType = .statement
            }
            
            let node = ASTNode(type: nodeType, identifier: String(trimmed.prefix(20)))
            
            // Infer depth hierarchy via indentation
            let leadingSpaces = line.prefix(while: { $0 == " " || $0 == "\t" }).count
            let targetDepth = max(1, (leadingSpaces / 4) + 1)
            
            while stack.count > targetDepth {
                stack.removeLast()
            }
            
            if let parent = stack.last {
                parent.children.append(node)
            }
            stack.append(node)
        }
        
        return root
    }
    
    /// Calculates the Cyclomatic Complexity for a given AST subtree.
    func calculateCyclomaticComplexity(node: ASTNode) -> Int {
        var complexity = 1
        func traverse(_ current: ASTNode) {
            if current.type == .controlFlow {
                complexity += 1
            }
            for child in current.children {
                traverse(child)
            }
        }
        traverse(node)
        return complexity
    }
}

// MARK: - Real-Time Audio Capture & Spectral Analysis

/// Captures microphone audio input and computes realtime RMS/spectral energy to modulate obfuscation dynamics.
final class SoundReactor: NSObject, AVCaptureAudioDataOutputSampleBufferDelegate {
    private let engine = AVAudioEngine()
    private(set) var currentEnergy: Float = 0.5
    
    override init() {
        super.init()
        setupAudioEngine()
    }
    
    private func setupAudioEngine() {
        let inputNode = engine.inputNode
        let format = inputNode.outputFormat(forBus: 0)
        
        inputNode.installTap(onBus: 0, bufferSize: 1024, format: format) { [weak self] buffer, _ in
            self?.processAudioBuffer(buffer)
        }
        
        do {
            try engine.start()
        } catch {
            // Fallback to synthetic energy modulations if audio hardware is unavailable
            startSyntheticReactor()
        }
    }
    
    private func processAudioBuffer(_ buffer: AVAudioPCMBuffer) {
        guard let channelData = buffer.floatChannelData?[0] else { return }
        let frameLength = Int(buffer.frameLength)
        
        var sum: Float = 0.0
        for i in 0..<frameLength {
            sum += channelData[i] * channelData[i]
        }
        
        let rms = sqrt(sum / Float(max(1, frameLength)))
        // Normalize RMS energy between 0.2 and 1.0
        self.currentEnergy = min(max(rms * 10.0, 0.2), 1.0)
    }
    
    private func startSyntheticReactor() {
        Timer.scheduledTimer(withTimeInterval: 0.1, repeats: true) { [weak self] _ in
            let phase = Date().timeIntervalSince1970 * 2.0
            self?.currentEnergy = Float((sin(phase) + 1.0) / 2.0 * 0.8 + 0.2)
        }
    }
}

// MARK: - MIDI Code Composition Engine

/// Translates AST structural metrics and real-time audio energy into a playable, evolving MIDI sequence.
final class MIDIObfuscatorEngine {
    private var musicPlayer: MusicPlayer?
    private var musicSequence: MusicSequence?
    private let analyzer = SourceAnalyzer()
    private let reactor = SoundReactor()
    
    // Scale degrees for a Pentatonic / Harmonic Minor scale to ensure musicality
    private let scaleDegrees: [UInt8] = [60, 62, 63, 65, 67, 68, 71, 72, 74, 75, 77, 79, 80, 83, 84]
    
    init() {
        NewMusicPlayer(&musicPlayer)
    }
    
    /// Translates source code into a sound-reactive MIDI composition.
    func translateToMIDI(sourceCode: String) -> [MIDINote] {
        let rootNode = analyzer.buildAST(from: sourceCode)
        var notes: [MIDINote] = []
        var currentTime: Double = 0.0
        
        func traverseAndCompose(node: ASTNode, depth: Int) {
            // Requirement: Pitch represents AST Node Depth
            let scaleIndex = min(depth, scaleDegrees.count - 1)
            let pitch = scaleDegrees[scaleIndex]
            
            // Requirement: Rhythm reflects Cyclomatic Complexity
            let complexity = analyzer.calculateCyclomaticComplexity(node: node)
            let baseDuration = 0.5 / Double(complexity)
            
            // Dynamically scale duration & velocity based on real-time sound reactivity
            let soundModulation = Double(reactor.currentEnergy)
            let duration = max(0.1, baseDuration * (1.5 - soundModulation))
            let velocity = UInt8(min(127, max(30, soundModulation * 127.0)))
            
            let midiNote = MIDINote(
                pitch: pitch,
                velocity: velocity,
                duration: duration,
                timestamp: currentTime
            )
            notes.append(midiNote)
            
            currentTime += duration
            
            for child in node.children {
                traverseAndCompose(node: child, depth: depth + 1)
            }
        }
        
        traverseAndCompose(node: rootNode, depth: 0)
        return notes
    }
    
    /// Synthesizes and plays the generated MIDI notes via CoreAudio.
    func performComposition(notes: [MIDINote]) {
        NewMusicSequence(&musicSequence)
        guard let sequence = musicSequence else { return }
        
        var track: MusicTrack?
        MusicSequenceNewTrack(sequence, &track)
        guard let musicTrack = track else { return }
        
        for note in notes {
            var channelNote = MIDINoteMessage(
                channel: 0,
                note: note.pitch,
                velocity: note.velocity,
                releaseVelocity: 0,
                duration: Float32(note.duration)
            )
            MusicTrackNewMIDINoteEvent(musicTrack, MusicTimeStamp(note.timestamp), &channelNote)
        }
        
        if let player = musicPlayer {
            MusicPlayerSetSequence(player, sequence)
            MusicPlayerPreroll(player)
            MusicPlayerStart(player)
        }
    }
}

// MARK: - Script Execution & Demonstration Setup

let sampleSourceCode = """
func obfuscateControlFlow(data: [Byte]) -> [Byte] {
    var result = [Byte]()
    if data.count > 0 {
        for byte in data {
            if byte % 2 == 0 {
                while result.count < 100 {
                    switch byte {
                    case 0x00:
                        result.append(0xFF)
                    default:
                        result.append(byte ^ 0xAA)
                    }
                }
            } else {
                result.append(byte)
            }
        }
    }
    return result
}
"""

let orchestrator = MIDIObfuscatorEngine()
let generatedNotes = orchestrator.translateToMIDI(sourceCode: sampleSourceCode)

print("--- SOUND-REACTIVE AST OBFUSCATION COMPOSITION ---")
print("Generated \(generatedNotes.count) MIDI notes driven by source code depth & complexity:")
for (index, note) in generatedNotes.prefix(10).enumerated() {
    print("Note [\(index)]: Pitch=\(note.pitch)Hz-equiv | Duration=\(String(format: "%.2f", note.duration))s | Velocity=\(note.velocity)")
}
print("Playing MIDI composition via CoreAudio...")

orchestrator.performComposition(notes: generatedNotes)

// Allow audio playback queue to complete before exiting
let totalDuration = generatedNotes.last?.timestamp ?? 5.0
Thread.sleep(forTimeInterval: totalDuration + 2.0)