#include <iostream>
#include <vector>
#include <cmath>
#include <chrono>
#include <thread>
#include <random>
#include <string>
#include <sstream>
#include <algorithm>

// Atmospheric state vector mutated by environmental fetch / simulation
struct AtmosphericState {
    float temperature = 18.5f; // Celsius
    float humidity    = 0.65f; // 0.0 - 1.0
    float windSpeed   = 12.0f; // km/h
    float pressure    = 1013.25f; // hPa
    float cloudCover  = 0.40f; // 0.0 - 1.0
};

// Bytecode Instruction Opcodes for the Esoteric Virtual Machine
enum Opcode : uint8_t {
    OP_NOP     = 0x00,
    OP_DRIFT   = 0x01, // Move coordinates by velocity vector
    OP_ROTATE  = 0x02, // Rotate velocity by wind vector angle
    OP_DENSE   = 0x03, // Modulate intensity using pressure/humidity
    OP_CHAOS   = 0x04, // Inject atmospheric turbulence entropy
    OP_WARP    = 0x05, // Non-linear spatial transformation (thermodynamics)
    OP_EMIT    = 0x06  // Write calculated pigment/energy to canvas frame
};

struct Instruction {
    Opcode op;
    uint8_t arg1;
    uint8_t arg2;
};

// Virtual VM executing atmospheric bytecode to generate visual canvas frame
class EsotericCanvasVM {
private:
    static constexpr int WIDTH = 80;
    static constexpr int HEIGHT = 30;
    std::vector<float> canvas;
    std::vector<float> energy;
    
public:
    EsotericCanvasVM() : canvas(WIDTH * HEIGHT, 0.0f), energy(WIDTH * HEIGHT, 0.0f) {}

    // Transmute raw atmospheric metrics into executable machine bytecode
    std::vector<Instruction> SynthesizeBytecode(const AtmosphericState& state) {
        std::vector<Instruction> program;
        std::mt19937 rng(static_cast<uint32_t>(state.pressure * 100 + state.temperature));
        std::uniform_int_distribution<int> dist(0, 255);

        // Bytecode length scaled dynamically with wind speed and energy flow
        size_t codeLength = static_cast<size_t>(60 + state.windSpeed * 3);

        for (size_t i = 0; i < codeLength; ++i) {
            uint8_t rawOp = dist(rng) % 7;
            // Introduce non-deterministic mutation derived from micro-fluctuations in humidity
            if ((dist(rng) / 255.0f) < state.humidity * 0.2f) {
                rawOp = (rawOp + 1) % 7;
            }
            program.push_back({static_cast<Opcode>(rawOp), static_cast<uint8_t>(dist(rng)), static_cast<uint8_t>(dist(rng))});
        }
        return program;
    }

    // Execute generated bytecode across the spatial lattice
    void ExecuteFrame(const std::vector<Instruction>& program, const AtmosphericState& state, float timeSec) {
        // Fade frame buffer (atmospheric dissipation)
        for (auto& val : canvas) val *= 0.88f;

        float x = WIDTH / 2.0f + std::sin(timeSec * 0.5f) * (WIDTH / 4.0f);
        float y = HEIGHT / 2.0f + std::cos(timeSec * 0.3f) * (HEIGHT / 4.0f);
        float vx = std::cos(state.windSpeed * 0.1f);
        float vy = std::sin(state.windSpeed * 0.1f);
        float density = state.humidity;

        for (const auto& instr : program) {
            switch (instr.op) {
                case OP_DRIFT:
                    x += vx * (instr.arg1 / 128.0f - 1.0f) * (state.windSpeed / 10.0f);
                    y += vy * (instr.arg2 / 128.0f - 1.0f) * (state.windSpeed / 10.0f);
                    break;

                case OP_ROTATE: {
                    float theta = (instr.arg1 / 255.0f) * 6.28318f + (state.temperature * 0.05f);
                    float nvx = vx * std::cos(theta) - vy * std::sin(theta);
                    float nvy = vx * std::sin(theta) + vy * std::cos(theta);
                    vx = nvx; vy = nvy;
                    break;
                }

                case OP_DENSE:
                    density = std::clamp(density + (instr.arg1 / 255.0f - 0.5f) * 0.2f, 0.01f, 1.0f);
                    break;

                case OP_CHAOS: {
                    float noise = std::sin(x * 0.1f + instr.arg1) * std::cos(y * 0.1f + instr.arg2);
                    vx += noise * (1.0f - state.cloudCover);
                    vy += noise * (1.0f - state.cloudCover);
                    break;
                }

                case OP_WARP:
                    x = std::fmod(x + WIDTH + (state.pressure - 1000.0f) * 0.05f, static_cast<float>(WIDTH));
                    y = std::fmod(y + HEIGHT + (state.temperature) * 0.05f, static_cast<float>(HEIGHT));
                    break;

                case OP_EMIT: {
                    int cx = static_cast<int>(x) % WIDTH;
                    int cy = static_cast<int>(y) % HEIGHT;
                    if (cx < 0) cx += WIDTH;
                    if (cy < 0) cy += HEIGHT;

                    size_t idx = cy * WIDTH + cx;
                    canvas[idx] = std::min(1.0f, canvas[idx] + density);
                    energy[idx] = instr.arg1 / 255.0f;
                    break;
                }

                default:
                    break;
            }
        }
    }

    // Render terminal canvas using esoteric luminance glyphs
    void Render() const {
        // ANSI escape sequence to move cursor to top-left corner
        std::cout << "\033[H";
        const char* palette = " .':---=*+%\x23@";
        const size_t palLen = 12;

        std::string frame = "";
        frame.reserve((WIDTH + 1) * HEIGHT);

        for (int y = 0; y < HEIGHT; ++y) {
            for (int x = 0; x < WIDTH; ++x) {
                float val = canvas[y * WIDTH + x];
                size_t palIdx = static_cast<size_t>(val * (palLen - 1));
                palIdx = std::min(palIdx, palLen - 1);
                frame += palette[palIdx];
            }
            frame += '\n';
        }
        std::cout << frame << std::flush;
    }
};

// Simulate real-time stream of non-deterministic atmospheric weather sensor data
AtmosphericState FetchLiveAtmosphere(float timeSec) {
    AtmosphericState state;
    // Micro-fluctuations mimicking atmospheric turbulence and thermal drifts
    state.temperature = 15.0f + 10.0f * std::sin(timeSec * 0.05f) + (std::rand() % 100) * 0.01f;
    state.humidity    = 0.50f + 0.30f * std::cos(timeSec * 0.08f);
    state.windSpeed   = 5.0f  + 20.0f * std::abs(std::sin(timeSec * 0.12f));
    state.pressure    = 1008.0f + 15.0f * std::sin(timeSec * 0.02f);
    state.cloudCover  = 0.20f + 0.70f * (std::sin(timeSec * 0.04f) * 0.5f + 0.5f);
    return state;
}

int main() {
    // Clear screen and hide cursor
    std::cout << "\033[2J\033[?25l";

    EsotericCanvasVM vm;
    auto startTime = std::chrono::steady_clock::now();

    // Render loop processing generative bytecode program execution
    for (int frame = 0; frame < 300; ++frame) {
        auto now = std::chrono::steady_clock::now();
        float timeSec = std::chrono::duration<float>(now - startTime).count();

        // 1. Ingest telemetry state
        AtmosphericState currentAtmo = FetchLiveAtmosphere(timeSec);

        // 2. Synthesize machine bytecode executable dynamically from environment
        std::vector<Instruction> bytecode = vm.SynthesizeBytecode(currentAtmo);

        // 3. Execute non-deterministic instruction execution on generative VM matrix
        vm.ExecuteFrame(bytecode, currentAtmo, timeSec);

        // 4. Render canvas frame
        vm.Render();

        std::this_thread::sleep_for(std::chrono::milliseconds(33)); // ~30 FPS frame rate
    }

    // Restore cursor visibility
    std::cout << "\033[?25h" << std::endl;
    return 0;
}